New workflow to deploy the lambda function
facebookexperimental/resctl-demo pull request #261
Opened 2022-02-16 12:48 UTC by kov

Build the lambda function, package it as expected by AWS lambda, then update it on AWS.

For now this is only triggered manually, so that the update can be performed only when it makes sense to the developers. In the future we can make a release being tagged trigger this workflow.

2022-02-16 14:52 UTC, obbardc requested changes

2022-02-16 14:52 UTC, obbardc commented on .github/workflows/ci.yaml
> +        run: cargo test
spurious change

2022-02-16 14:52 UTC, obbardc commented on .github/workflows/lambda.yaml
> +on:
I think we should also upload when a new version is tagged too, since we may forget to manually trigger the workflow:

```suggestion
on:
  push:
    tags:
    - 'v*'
```

2022-02-16 14:52 UTC, obbardc commented on .github/workflows/lambda.yaml
> +          aws-region: eu-west-1
can we add the region to the secrets too ?

2022-03-09 12:13 UTC, kov commented
> we should probably explain what secrets need to be added too

explain where? I can add it to the doc on deploying the lambda function I guess, after it has been validated

2023-05-30 21:19 UTC, davide125 requested changes

2023-05-30 21:19 UTC, davide125 commented on .github/workflows/lambda.yaml
> +          aws-region: ${{ secrets.AWS_REGION }}
We need to use OIDC instead of static creds here. Per https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services we need to drop the `aws-access-key-id` and `aws-secret-access-key` here and add

```
permissions:
  id-token: write
  contents: read
```

at the job or workflow level

2023-05-30 21:20 UTC, davide125 commented on .github/workflows/lambda.yaml
> +          role-to-assume: IoCostLambdaManager
Also I think this needs to be a full arn so it might be better to make it pull from secrets too

2023-06-01 19:51 UTC, davide125 commented on .github/workflows/lambda.yaml
> +          cargo build --release --all-features --target x86_64-unknown-linux-musl
I think we just need `--features lambda` for this, per https://github.com/facebookexperimental/resctl-demo/blob/efd6ad0ffa9f391920f622f5e1c8be649d9bb89f/resctl-bench/doc/lambda.md#building

2023-06-13 13:19 UTC, santoshmahto7 commented on .github/workflows/lambda.yaml
> +          aws-region: ${{ secrets.AWS_REGION }}
DONE in recent push, but as I read we  also need to also configure OIDC provider on aws 
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-the-identity-provider-to-aws. 
Not sure if it's already enabled there.
Could you confirm on this

2023-06-13 13:21 UTC, santoshmahto7 commented on .github/workflows/lambda.yaml
> +          cargo build --release --all-features --target x86_64-unknown-linux-musl
applied the same.

2023-06-13 15:55 UTC, merged