Merge summary
facebookexperimental/resctl-demo pull request #277
Opened 2022-06-03 13:56 UTC by kov

I am wondering if we should just show the minimum number of points and the maximum for ouliers and errors instead of showing all of the solutions. What information would you like to have here? This is what it looks like right now:

```
==========================================================================================

[0] iocost-tune
  version: 2.2
  memory-profile: 16
  storage: Samsung SSD 970 PRO 512GB
  classifier: dither,vrate-max=125
  sources:
    + ../result-files/2.2/970pro.json.gz

==========================================================================================

[MOF]
23 points, 0 outliers, error: 0.005026878511151166

[isol]
23 points, 0 outliers, error: 0.002473790887859725

[aMOF]
23 points, 0 outliers, error: 0.010598882713881336

[aMOF-delta]
23 points, 0 outliers, error: 0.014563493384749826

[lat-imp]
23 points, 0 outliers, error: 0.00228160166650453

[work-csv]
23 points, 0 outliers, error: 0.007252992610439838

[rlat-50-mean]
22 points, 1 outliers, error: 0.000003165294757708039

[rlat-99-mean]
22 points, 1 outliers, error: 0.00004883318499949513

[rlat-50-99]
21 points, 2 outliers, error: 0.00004118668882641492

[rlat-99-99]
21 points, 2 outliers, error: 0.00018015485774651135

[rlat-50-100]
22 points, 1 outliers, error: 0.00013802052188441994

[rlat-100-100]
22 points, 1 outliers, error: 0.04568097353998776

[wlat-50-mean]
21 points, 2 outliers, error: 0.000004729969520701066

[wlat-99-mean]
22 points, 1 outliers, error: 0.00011031272310534356

[wlat-50-99]
22 points, 1 outliers, error: 0.000008498092655295324

[wlat-99-99]
21 points, 2 outliers, error: 0.002581282782736685

[wlat-50-100]
22 points, 1 outliers, error: 0.000048060689421551766

[wlat-100-100]
22 points, 1 outliers, error: 0.04497661968502278
```

By the way, I thought about changing the `full` member of FormatOpts to be an enum with a 'mode' of Full, Summary, MergeSummary, but after looking at how invasive the patch was getting I backtracked. Let me know if you would prefer that.

2022-06-08 21:26 UTC, htejun commented
Let's just show MOF and aMOF as they're the important ones. Other information which might be useful is the base params and the scale factor of each solution, so how about sth like the following:
```
23 data points, MOF=[1.12, 1.42], aMOF=[1.10, 1.30]
base model params: rbps=1.5G riops=124k wbps=...
solutions: naive=100% bandwidth=100% isolated-bandwidth=57.61% isolation=52.75%
                  rlat-99-q1=100% rlat-99-q2=54.23% ...
```

2022-06-09 19:23 UTC, htejun commented
That looks great.

* Yeah, it'd be better if the print ordering follows the same order that iocost-tune result output follows.
* Maybe use format_size() when printing out the model params?
* It being its own sub-command bothers me a little bit. It's definitely not a huge issue but I'm sure you structured it that way for a reason. Can you elaborate the justificaiton a bit?

Thanks.

2022-06-10 14:02 UTC, kov commented
>     * Yeah, it'd be better if the print ordering follows the same order that iocost-tune result output follows.

Will do!

>     * Maybe use format_size() when printing out the model params?

doh =) I missed that one

>     * It being its own sub-command bothers me a little bit. It's definitely not a huge issue but I'm sure you structured it that way for a reason. Can you elaborate the justificaiton a bit?

It was mostly for convenience, really, as it's easier to find and to get right. On second thought, I guess it makes more sense as a parameter as you had mentioned before as it will allow for the reports being more flexible, and gives us a lot more room to customize the output going forward. Will also be less invasive.

> 
> 
> Thanks.

2022-06-10 17:49 UTC, htejun requested changes

2022-06-10 17:49 UTC, htejun commented on resctl-bench/doc/iocost-tune.md
> +High level view
Wouldn't this fit better under 'Format properties' where pdf is documented too?

2022-06-10 17:49 UTC, htejun commented on resctl-bench/src/bench/iocost_tune.rs
> +                "high-level" => high_level = v.len() > 0 || v.parse::<bool>()?,
So, it's a bit weird but the convention is to parse bool as `v.len() == 0 || v.parse::<bool>()?` so that users can just say `iocost-tune:high-level` instead of always having to specify the value.

2022-06-10 18:25 UTC, kov commented on resctl-bench/src/bench/iocost_tune.rs
> +                "high-level" => high_level = v.len() > 0 || v.parse::<bool>()?,
Makes sense, I read it too quickly and for some reason thought the non-parse case would mean defaulting to true if the key is not there, but it's just the value...

2022-06-10 18:54 UTC, merged