Enable resctl-bench log dumping to file.
facebookexperimental/resctl-demo pull request #293
Opened 2023-08-09 17:41 UTC by santoshmahto7

If environment variable LOG_DUMP_FILE=<filename>
is set then resctl-bench will also dump terminal logs to the specified filename in environment variable.

Storing of log is required for debugging purposes.

2023-08-09 21:49 UTC, htejun requested changes

2023-08-09 21:49 UTC, htejun commented on rd-util/src/lib.rs
> +        if !std::env::var("LOG_DUMP_FILE").is_ok() {
Wouldn't it be better for this to be an explicit option instead of an environment variable? RUST_LOG environment is kinda special in that it's widespread but in general it's better to make them explicit options as they're discoverable and consistent with other options.

2023-08-09 21:49 UTC, htejun commented on rd-util/src/lib.rs
> +        if !std::env::var("LOG_DUMP_FILE").is_ok() {
It's also rather odd to have
```
if (!COND) {
} else {
}
```
Just flip the two blocks and lose the negation?

2023-08-09 21:49 UTC, htejun commented on rd-util/src/lib.rs
> +                sl::WriteLogger::init(sl_level, lcfg.build(), std::io::stderr()).unwrap();
If target log file is specified, that should be written to whether console is user attended or not, right? ie. logfile should be initialized in the common path and what changes depending user-attendedness is whether to combine it with TermLogger or WriteLogger.

2023-08-23 12:05 UTC, santoshmahto7 commented on rd-util/src/lib.rs
> +        if !std::env::var("LOG_DUMP_FILE").is_ok() {
sure, I will adapt code to use option rather than env variable and also change if condition.

2023-08-23 12:06 UTC, santoshmahto7 commented on rd-util/src/lib.rs
> +                sl::WriteLogger::init(sl_level, lcfg.build(), std::io::stderr()).unwrap();
you're right, it's error on my side. Will correct it

2023-08-24 22:46 UTC, htejun approved these changes

2023-09-06 18:14 UTC, merged